# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7448f405770890b0eafd819524bac297ecca61636e047c4e85e6fe9c09d674589b62f845e0e59af27c0ca42d0fb65c7453310c2a09e678a1becde3ad00f91450

test:
  secret_key_base: 73163b68affc399038ba55056af1bcf4bf0598fbf2af4ca1d475aa82277da32cf8fc031d43c7f9b37cb5fa646818590aeaee01f123bc9110fb4bc439b24214b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
